# Generated by Django 4.0.4 on 2022-06-12 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('phone', models.IntegerField(default=20)),
                ('details', models.CharField(max_length=32)),
                ('img_url', models.ImageField(default='', upload_to='img')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now)),
                ('creator', models.IntegerField(default=0)),
                ('pic', models.ImageField(upload_to='pic/', verbose_name='图片地址')),
            ],
            options={
                'db_table': 'activities',
            },
        ),
    ]
