# Generated by Django 4.0.4 on 2022-06-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myact', '0002_alter_activities_details_alter_activities_img_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='pic',
        ),
        migrations.AlterField(
            model_name='activities',
            name='img_url',
            field=models.ImageField(upload_to='pic/', verbose_name='图片地址'),
        ),
    ]
