# Generated by Django 4.0.4 on 2022-06-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myact', '0003_remove_activities_pic_alter_activities_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='img_url',
        ),
        migrations.AddField(
            model_name='activities',
            name='Photo',
            field=models.ImageField(default='user1.jpg', upload_to='photos'),
        ),
    ]
