# Generated by Django 4.0.4 on 2022-06-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myact', '0006_alter_activities_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='image',
            field=models.ImageField(default='user1.jpg', upload_to='pic/'),
        ),
    ]
