# Generated by Django 4.0.4 on 2022-06-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myact', '0007_alter_activities_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='image_name',
            field=models.CharField(default='abc', max_length=100),
        ),
        migrations.AlterField(
            model_name='activities',
            name='image',
            field=models.ImageField(upload_to='pic/', verbose_name='图片地址'),
        ),
    ]
