# Generated by Django 4.0.4 on 2022-06-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myact', '0009_alter_activities_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='image',
            field=models.ImageField(upload_to='media/', verbose_name='图片地址'),
        ),
    ]
