# Generated by Django 4.0.4 on 2022-06-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myact', '0010_alter_activities_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='image',
            field=models.ImageField(default='fuckyou..jpg', upload_to='media'),
        ),
    ]
