# Generated by Django 4.0.4 on 2022-07-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
